- hosts: all
  become: yes
  vars:
    apache_packages:
      Ubuntu:
        - apache2
        - libapache2-mod-php
      CentOS:
        - httpd
        - php

  tasks:

    - name: Update package cache
      package:
        update_cache: yes

    - name: Install Apache + PHP
      package:
        name: "{{ apache_packages[ansible_distribution] }}"
        state: latest